# numpy 编程基础
- NumPy 官网 http://www.numpy.org/
- NumPy 源代码：https://github.com/numpy/numpy
- 科学计算和数据分析的基础包

- 数组是numpy库的中央数据结构。数组是值的网格，它包含有关原始数据，如何定位元素以及如何解释元素的信息。它具有可以以各种方式建立索引的元素网格。元素都是相同的类型，称为array dtype。
- ndarray ('n维数组' 的简写)是numpy的核心概念，它是一系列<span class="burk">同类型数据</span>组成的数组，可以是一维或多维数组
- 结构数组允许异质数组结构 

In [264]:
import numpy as np 
print('''调用numpy 模块或函数时，应该使用np.模块或者函数名称的方式。''')
print("- -"*30)
print('''查看numpy模块内的函数。''')
a = dir(np)
#print(a)
print("- -"*30)
print('''查看numpy模块的版本。''')
np.__version__

调用numpy 模块或函数时，应该使用np.模块或者函数名称的方式。
- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
查看numpy模块内的函数。
- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
查看numpy模块的版本。


'1.18.1'

# 数组的创建

## 创建一维数组

In [35]:
print("- -"*15,'用普通方法生成一维数组',"- -"*15)  # 分割线
num = [0 for i in range(1,5)]  # 创建一维数组
print(num)  # 打印数组
num1 = ['Li',1,2,3,3.2]
print('列表中的元素类型可以不相同',num1)
print("- -"*15,'下面介绍numpy模块创建数组的方法',"- -"*15)  # 分割线

- -- -- -- -- -- -- -- -- -- -- -- -- -- -- - 用普通方法生成一维数组 - -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
[0, 0, 0, 0]
列表中的元素类型可以不相同 ['Li', 1, 2, 3, 3.2]
- -- -- -- -- -- -- -- -- -- -- -- -- -- -- - 下面介绍numpy模块创建数组的方法 - -- -- -- -- -- -- -- -- -- -- -- -- -- -- -


### arange()方法
- 语法    numpy.arange(start, stop, step, dtype = None)
- 在给定间隔内返回均匀间隔的值，值在包括start但不包括stop的区间,返回的是 ndarray 。

In [38]:
import numpy as np 
v = np.arange(10,dtype=int)
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
import numpy as np 
v = np.arange(10,step=2.5,dtype=float)
v.dtype
v

array([0. , 2.5, 5. , 7.5])

### linspace()方法: 产生等差数列
- 语法 linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
- retstep : bool. If True, return (`samples`, `step`), where `step` is the spacing between samples. retstep会改变计算的输出，输出一个元组，而元组的两个元素分别是需要生成的数列和数列的步进差值。


In [45]:
a = np.linspace(1,19,10)
a

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.])

###  logspace()方法：产生等比数列

In [147]:
#可直接创建一维的由等比数列组成的数组，可指定开始和结束数值，以及数列包含的数字数量
'''np.logspace(
    start, #序列的起始值
    stop, #序列的终止值为：base ** stop。如果endpoint为true，该值包含于数列中
    num=50, #要生成的等步长的样本数量，默认为50
    endpoint=True, #该值为 true 时，数列中中包含stop值，反之不包含，默认是True。
    base=10.0,  #对数 log 的底数。
    dtype=None #不再赘述
)
 '''
import numpy as np
from math import e
np.logspace(1,5,5,base=e)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

### 创建对角矩阵数组

In [152]:
'''#可创建对角线矩阵
np.eye(
    N, #指定对角矩阵的行数
    M=None, #指定对角矩阵的列数，默认与N相等
    k=0, #对角线的索引，默认为0，即斜对角，如果赋予正值或负值，则会相对向右上或左下移动
    dtype=float,  #不再赘述
    order='C'
)'''
 
import numpy as np
a = np.eye(5,dtype=int)
a.ndim

2

### 特殊数组：全0/1数组
- zeros数组：全零数组，元素全为零。
- ones数组：全1数组，元素全为1。
- empty数组：创建一个内容随机且依赖于内存状态的向量。
- 以上三个函数均可以产生多元数组。

In [77]:
x = np.zeros(10)
'''语法： zeros(shape, dtype=float, order='C')'''
'''可以产生多元数组如 np.zeros((3,4))'''
#help(np.zeros)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [67]:
x = np.ones(20)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [76]:
x1 = np.empty((3,4),np.int)
x1

array([[ 1885941401,  1073308081, -2104352480,  1073094847],
       [ 1507217317,  1072516558,   864273760,  1067754983],
       [ -627551566,  1072153251,  1754293168,  1073418987]])

### 随机数组

In [83]:
print("- -"*15,'高斯分布的随机数(一)',"- -"*15)
'''np.random.randn(d0,d1,...dn)：生成对应的标准的高斯分布随机数'''
print('标准高斯分布的随机数+二维数组',np.random.randn(2,3))

print("- -"*15,'高斯分布的随机数(二)',"- -"*15)
'''np.random.normal(loc, scale, size)：生成均值为loc，标准差为scale，大小为size的高斯分布随机数'''
x = np.random.normal(1,1,10)
print("一般的高斯分布的随机数",x)
x = np.random.normal(1,1,(2,3))
print("一般的高斯分布的随机数+二维数组",x)

- -- -- -- -- -- -- -- -- -- -- -- -- -- -- - 高斯分布的随机数(一) - -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
标准高斯分布的随机数+二维数组 [[ 1.02451632  2.14325302 -0.96544785]
 [-0.25607679  1.12515145 -0.40051724]]
- -- -- -- -- -- -- -- -- -- -- -- -- -- -- - 高斯分布的随机数(二) - -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
一般的高斯分布的随机数 [-0.93870094 -0.52932362  1.74854311  0.49922881  1.28462598  0.92733802
  0.42558788  0.44365482  0.97052676  1.54326362]
一般的高斯分布的随机数+二维数组 [[ 1.67724202  2.52283387  1.88909515]
 [ 0.59776421 -0.13757208  2.13721878]]


In [85]:
print("- -"*15,'均匀分布的随机数(一)',"- -"*15)
'''np.random.rand(shape)：生成对应形状（shape）的[0,1]均匀分布的随机数'''
x = np.random.rand(2,3)
print(x)
print("- -"*15,'均匀分布的随机数(二)',"- -"*15)
'''np.random.uniform(low, high, size)：生成一个从[low, high)中随即采样的，样本数量为size的均匀分布随机数'''
x1 = np.random.uniform(0,1,10)
print(x1)
'''如何产生其它分布的随机数？'''

- -- -- -- -- -- -- -- -- -- -- -- -- -- -- - 均匀分布的随机数(一) - -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
[[0.74545452 0.20294491 0.20069759]
 [0.14923271 0.75442628 0.70120174]]
- -- -- -- -- -- -- -- -- -- -- -- -- -- -- - 均匀分布的随机数(二) - -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
[0.4427768  0.28877574 0.4876246  0.06657145 0.47267468 0.27346376
 0.81062662 0.56814251 0.34885429 0.36801066]


'如何产生其它分布的随机数？'

## 二维数组

In [106]:
'''普通方法生成'''
num = [[1 for i in range(1,5)]for j in range(1,5)]
print(num)  # 打印数组
print("- -"*50)  # 分割线

'''等价的方法'''
np.ones((4,4),dtype=int)

[[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]]
--------------------------------------------------


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [154]:
#一般使用array构造函数创建ndarray
print('''import numpy as np
np.array(
    object, #传入列表、元组来创建一维数组，或列表、元组的嵌套创建多维数组
    dtype = None, #设置数组元素的数据类型，可以是内置的数据类型，也可是自定义的结构化数据类型
    copy = True,  #设置传入的对象是否需要复制，默认是True，如果设置为False，则会直接引用，一般用不到
    order = None, #设置创建数组的样式，C为行方向，F为列方向，A为任意方向（默认）,一般无需显示设置
    subok = False, #默认返回一个与基类类型一致的数组，暂时还未用到过
    ndmin = 0 #指定生成数组的最小维度，如果传入的object维度没达到最小维度，则会自定转变为最小维度的数组
)''')

import numpy as np
np.array(
    object, #传入列表、元组来创建一维数组，或列表、元组的嵌套创建多维数组
    dtype = None, #设置数组元素的数据类型，可以是内置的数据类型，也可是自定义的结构化数据类型
    copy = True,  #设置传入的对象是否需要复制，默认是True，如果设置为False，则会直接引用，一般用不到
    order = None, #设置创建数组的样式，C为行方向，F为列方向，A为任意方向（默认）,一般无需显示设置
    subok = False, #默认返回一个与基类类型一致的数组，暂时还未用到过
    ndmin = 0 #指定生成数组的最小维度，如果传入的object维度没达到最小维度，则会自定转变为最小维度的数组
)


In [118]:
import numpy as np
m1= np.array([np.arange(1,4),np.arange(4,7),np.arange(7,10),np.arange(10,13),np.arange(13,16),np.arange(16,19)])  # 创建6行3列的二维数组
print(m1)
print("- -"*15,'array要求数据的类型相同',"- -"*15) 
m2= np.array([np.arange(1,4),np.arange(4,7),np.arange(7,10),np.arange(10,13),np.arange(13,16),np.arange(16,19),['li','liu','zhang']])  
print(m2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
- -- -- -- -- -- -- -- -- -- -- -- -- -- -- - array要求数据的类型相同 - -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
[['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']
 ['10' '11' '12']
 ['13' '14' '15']
 ['16' '17' '18']
 ['li' 'liu' 'zhang']]
- -- -- -- -- -- -- -- -- -- -- -- -- -- -- - 描述数据的元组数据组成 - -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
(6, 3)
2
44


## 结构数组

In [137]:
name = ['Alice','Bob','Cathy','Doug']
age = [25,45,37,19]
weight = [55.0, 85.5, 68.0, 61.5]
dict(姓名=name,年龄=age,体重=weight)


{'姓名': ['Alice', 'Bob', 'Cathy', 'Doug'],
 '年龄': [25, 45, 37, 19],
 '体重': [55.0, 85.5, 68.0, 61.5]}

In [221]:
print('''Python 中的数据类型
默认情况下，Python 拥有以下数据类型：

strings - 用于表示文本数据，文本用引号引起来。例如 "ABCD"。
integer - 用于表示整数。例如 -1, -2, -3。
float - 用于表示实数。例如 1.2, 42.42。
bool - 用于表示 True 或 False。
complex - 用于表示复平面中的数字。例如 1.0 + 2.0j，1.5 + 2.5j。''')

Python 中的数据类型
默认情况下，Python 拥有以下数据类型：

strings - 用于表示文本数据，文本用引号引起来。例如 "ABCD"。
integer - 用于表示整数。例如 -1, -2, -3。
float - 用于表示实数。例如 1.2, 42.42。
bool - 用于表示 True 或 False。
complex - 用于表示复平面中的数字。例如 1.0 + 2.0j，1.5 + 2.5j。


In [225]:
print('''numpy 有一些额外的数据类型，并通过一个字符引用数据类型，例如 i 代表整数，u 代表无符号整数等。

以下是 numpy 中所有数据类型的列表以及用于表示它们的字符。

i - 整数
b - 布尔
u - 无符号整数
f - 浮点
c - 复合浮点数
m - timedelta
M - datetime
O - 对象
S - 字符串
U - unicode 字符串
V - 固定的其他类型的内存块 ( void )

对于 i、u、f、S 和 U，我们也可以定义大小。''')

numpy 有一些额外的数据类型，并通过一个字符引用数据类型，例如 i 代表整数，u 代表无符号整数等。

以下是 numpy 中所有数据类型的列表以及用于表示它们的字符。

i - 整数
b - 布尔
u - 无符号整数
f - 浮点
c - 复合浮点数
m - timedelta
M - datetime
O - 对象
S - 字符串
U - unicode 字符串
V - 固定的其他类型的内存块 ( void )

对于 i、u、f、S 和 U，我们也可以定义大小。


In [224]:
print('''查看完整的ndarry数据类型''')
a = set(np.typeDict.values())
print(a)

查看完整的ndarry数据类型
{<class 'numpy.uint32'>, <class 'numpy.str_'>, <class 'numpy.datetime64'>, <class 'numpy.float32'>, <class 'numpy.bool_'>, <class 'numpy.float64'>, <class 'numpy.clongdouble'>, <class 'numpy.float16'>, <class 'numpy.bytes_'>, <class 'numpy.uint16'>, <class 'numpy.complex64'>, <class 'numpy.complex128'>, <class 'numpy.timedelta64'>, <class 'numpy.int32'>, <class 'numpy.uint8'>, <class 'numpy.longdouble'>, <class 'numpy.void'>, <class 'numpy.int64'>, <class 'numpy.uintc'>, <class 'numpy.object_'>, <class 'numpy.int8'>, <class 'numpy.intc'>, <class 'numpy.uint64'>, <class 'numpy.int16'>}


In [228]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [219]:
'''numpy 模块如何存储不同类型的数据?

结构化数组的数据类型有多种制定方式：'''
# 1. 采用字典的方法：两个键：names(定义每个字段的名称)和formats（）定义每个字段的类型
array1 = np.dtype({'names':('name', 'age', 'weight'),'formats':('U10', 'i4', 'f8')})
print(array1)
# 2. 数值数据类型可以用Python类型和numpy的dtype类型指定：
array2 = np.dtype({'names':('name', 'age', 'weight'),'formats':((np.str_, 10), int, np.float32)})
print(array2)
# 3. 使用元组的方式：
array3 = np.dtype([('name', 'S10'), ('age', 'i4'), ('weight', 'f8')])
print(array3)
print('定义号好数据类型后, 便可以构造结构数组:')
a = np.array([('abc', 21, 50),('xyz', 18, 75)], dtype =array1) 
print(a)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]
[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')]
[('name', 'S10'), ('age', '<i4'), ('weight', '<f8')]
定义号好数据类型后, 便可以构造结构数组:
[('abc', 21, 50.) ('xyz', 18, 75.)]


## 从已有的数据创建数组

In [141]:
print('''np.asarray(a, dtype = None, order = None)
a:任意形式的输入参数，可以是，列表, 列表的元组, 元组, 元组的元组, 元组的列表，
多维数组
order: "C"和"F"两个选项,分别代表，行优先和列优先，在计算机内存中的存储元素的顺序。''')

np.asarray(a, dtype = None, order = None)
a:任意形式的输入参数，可以是，列表, 列表的元组, 元组, 元组的元组, 元组的列表，
多维数组
order: "C"和"F"两个选项,分别代表，行优先和列优先，在计算机内存中的存储元素的顺序。


In [287]:
x =  [(1,2,3),(4,5)] 
a = np.asarray(x)  
print (a)
a.shape
a.ndim
print(np.array(x))

[(1, 2, 3) (4, 5)]
[(1, 2, 3) (4, 5)]


# 索引和切片

## 基本索引与切片

In [163]:
'''因矩阵或数组，其实本质是由列表组成，故也可以使用与访问Python列表元素相同的方式对数组进行切片和索引访问。'''
import numpy as np
m1= np.array([np.arange(1,4),np.arange(4,7),np.arange(7,10),np.arange(10,13),np.arange(13,16),np.arange(16,19)])  # 创建6行3列的二维数组
print(m1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [176]:
import numpy as np
m1= np.array([np.arange(1,4),np.arange(4,7),np.arange(7,10),np.arange(10,13),np.arange(13,16),np.arange(16,19)])  # 创建6行3列的二维数组

In [181]:
'''1、使用索引切片访问和提取数组的一部分'''
print('- -'*5,'提取1到6行每隔1行取一行，及1到2列的数据','- -'*5)

print(m1[0:5:2,0:2]) #会并组成一个2*3矩阵

'''2、提取指定的行、列: 用，表示不同的维度'''
print('- -'*5,'提取第3行的数据','- -'*5)
print(m1[2,:]) 
print('- -'*5,'提取第3列','- -'*5)
print(m1[:,2])

'''3、提取指定的元素''' 
print('- -'*5,'提取第2行的第二列元素','- -'*5)
print(m1[1,1])
 
'''4、一维及更高维，同理，比如提取shape为3*4*5的矩阵，则即a[k,m,n]，其中京k、m、n即可以是索引值，也可以是由索引值构成的切片'''
'''5、切片中省略号的用法''' 

print('- -'*5,'当要提取某一整行或整列时，其效果与：完全相同','- -'*5)
print('m1[:,2] 等同于m1[...,2]:即提取数组的第二列数据\n',m1[...,2])

print('m1[2,:] 等同于m1[2,...]:即提取数组的第二行数据\n',m1[2,...])

 
'''6、切片对象可以通过内置的 slice 函数，并设置 start, stop 及 step 参数进行，从原数组中切割出一个新数组。'''
s=slice(1,3)
m1[s] #等同于m1[1:3]

- -- -- -- -- - 提取1到6行每隔1行取一行，及1到2列的数据 - -- -- -- -- -
[[ 1  2]
 [ 7  8]
 [13 14]]
- -- -- -- -- - 提取第3行的数据 - -- -- -- -- -
[7 8 9]
- -- -- -- -- - 提取第3列 - -- -- -- -- -
[ 3  6  9 12 15 18]
- -- -- -- -- - 提取第2行的第二列元素 - -- -- -- -- -
5
- -- -- -- -- - 当要提取某一整行或整列时，其效果与：完全相同 - -- -- -- -- -
m1[:,2] 等同于m1[...,2]:即提取数组的第二列数据
 [ 3  6  9 12 15 18]
m1[2,:] 等同于m1[2,...]:即提取数组的第二行数据
 [7 8 9]


slice(1, 3, None)

## 花式索引访问
- 指利用整数数组进行索引，使用指定顺序对数组提取子集。
- 使用一维整型数组作为索引时，
  如果目标是一维数组，那么索引的结果就是对应位置的元素（类似索引访问）；
  如果目标是二维数组，那么就是对应下标的行（类似直接取对应的行）

In [182]:
'''1.原数组为一维数组，传入1个一维数组作为索引.'''
a=np.array([1,2,3,4,5,6])
a[[1,2,3]] #得到a的第2、3、4个元素并组成一个新的一维数组

array([2, 3, 4])

In [201]:
'''2.原数组为二维数组，传入1个一维数组作为索引'''
a=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
a[[1,2]] #得到a的第2和第3行组成的2*3数组


array([[1, 2, 3],
       [4, 5, 6]])

In [218]:
'''3.原数组为多维数组，传入多个一维数组作为索引'''
b = np.arange(24).reshape(2,3,4)
print(b)
print("- -"*5, '提取第0层第1行第2列、第0层第2行第3列的数据集','- -'*10)
index = [[0],[1,2],[2,3]]#将被弃用
#b[index]
index = ([0],[1,2],[2,3])#将多个一维数组放在元组内；层，行列，行列
print(b[index])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
- -- -- -- -- - 提取第0层第1行第2列、第0层第2行第3列的数据集 - -- -- -- -- -- -- -- -- -- -
[ 6 11]


In [221]:
'''4. 原数组为多维数组，传入多个一维数组作为索引，且使用ix_ 函数
ix_函数将多个一维数组转换为一个用于选取矩形区域的索引器
#pandas内的iloc索引方式，其本质即ix_的索引方式'''
index = np.ix_([0],[1,2],[2,3]) #层，行，列
print(b[index])
print("- -"*5, '''第0层的第1行的第2列和第3列,和第2行的的第2列和第3列元素''','- -'*10)

[[[ 6  7]
  [10 11]]]
- -- -- -- -- - 第0层的第1行的第2列和第3列,和第2行的的第2列和第3列元素 - -- -- -- -- -- -- -- -- -- -


In [212]:
index1 = np.ix_([1,0],[2,1],[0,3,2])
b[index1]

array([[[20, 23, 22],
        [16, 19, 18]],

       [[ 8, 11, 10],
        [ 4,  7,  6]]])

## 逻辑索引
- 使用布尔型索引、条件索引

In [222]:
b = np.arange(24).reshape(2,3,4)
b[b>=15]

array([15, 16, 17, 18, 19, 20, 21, 22, 23])

In [227]:
b = np.arange(24).reshape(2,3,4)
b[~(b>=15)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [232]:
b = np.arange(24).reshape(2,3,4)
b[(b<20)&(b>=15)]
b[(b>20)|(b>=15)]
'''and 和 or 布尔数组中无效'''

'and 和 or 布尔数组中无效'

In [233]:
'''
#布尔索引，可以使用布尔表达式（条件表达式）来检索出某个数组符合指定条件的元素，并返回由这些元素组成的一维数组

#布尔索引在理解pandas相关条件检索操作时，很有用，可以说pandas的条件检索，本质就是布尔索引

#其本质的运算逻辑即对数组进行遍历，找出满足条件的元素对应的索引值，最后返回索引值对应的元素
'''

'\n#布尔索引，可以使用布尔表达式（条件表达式）来检索出某个数组符合指定条件的元素，并返回由这些元素组成的一维数组\n\n#布尔索引在理解pandas相关条件检索操作时，很有用，可以说pandas的条件检索，本质就是布尔索引\n#其本质的运算逻辑即对数组进行遍历，找出满足条件的元素对应的索引值，最后返回索引值对应的元素\n'

# 数组的属性

In [123]:
import numpy as np
m1= np.array([np.arange(1,4),np.arange(4,7),np.arange(7,10),np.arange(10,13),np.arange(13,16),np.arange(16,19)])  # 创建6行3列的二维数组
#print(m1)
print("- -"*15,'数组的属性',"- -"*15) 
print(m1.shape)#shape属性表示数组的形状
print(m1.ndim)#ndim属性表示数组的维数
print(m2.itemsize)#itemsize 属性表示元素大小：即该数组内元素占据内存大小，字节单位

- -- -- -- -- -- -- -- -- -- -- -- -- -- -- - 数组的属性 - -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
(6, 3)
2
44


In [125]:
print('''其它的数组属性
ndarray.ndim	秩，即轴的数量或维度的数量
ndarray.shape	数组的维度，对于矩阵，n 行 m 列
ndarray.size	数组元素的总个数，相当于 .shape 中 n*m 的值
ndarray.dtype	ndarray 对象的元素类型
ndarray.itemsize	ndarray 对象中每个元素的大小，以字节为单位
ndarray.flags	ndarray 对象的内存信息
ndarray.real	ndarray元素的实部
ndarray.imag	ndarray 元素的虚部
ndarray.data	包含实际数组元素的缓冲区，由于一般通过数组的索引获取元素，所以通常不需要使用这个属性。''')

其它的数组属性
ndarray.ndim	秩，即轴的数量或维度的数量
ndarray.shape	数组的维度，对于矩阵，n 行 m 列
ndarray.size	数组元素的总个数，相当于 .shape 中 n*m 的值
ndarray.dtype	ndarray 对象的元素类型
ndarray.itemsize	ndarray 对象中每个元素的大小，以字节为单位
ndarray.flags	ndarray 对象的内存信息
ndarray.real	ndarray元素的实部
ndarray.imag	ndarray 元素的虚部
ndarray.data	包含实际数组元素的缓冲区，由于一般通过数组的索引获取元素，所以通常不需要使用这个属性。


#  数组操作

numpy 中包含了一些函数用于处理数组，大概可分为以下几类：

- 修改数组形状
- 翻转数组
- 修改数组维度
- 连接数组
- 分割数组
- 数组元素的添加与删除

## 修改数组形状

In [235]:
print('''
函数	描述
reshape	不改变数据的条件下修改形状
flat	数组元素迭代器
flatten	返回一份数组拷贝，对拷贝所做的修改不会影响原始数组
ravel	返回展开数组''')


函数	描述
reshape	不改变数据的条件下修改形状
flat	数组元素迭代器
flatten	返回一份数组拷贝，对拷贝所做的修改不会影响原始数组
ravel	返回展开数组


In [236]:
print('''np.reshape 函数可以在不改变数据的条件下修改形状，格式如下： 
          np.reshape(arr, newshape, order='C')
arr：要修改形状的数组
newshape：整数或者整数数组，新的形状应当兼容原有形状
order：'C' -- 按行，'F' -- 按列，'A' -- 原顺序，'k' -- 元素在内存中的出现顺序。''')

np.reshape 函数可以在不改变数据的条件下修改形状，格式如下： 
          np.reshape(arr, newshape, order='C')
arr：要修改形状的数组
newshape：整数或者整数数组，新的形状应当兼容原有形状
order：'C' -- 按行，'F' -- 按列，'A' -- 原顺序，'k' -- 元素在内存中的出现顺序。


In [242]:
import numpy as np 
a = np.arange(10)
print ('原始数组：',a,'\n')
print("- -"*20) 
b = a.reshape(2,5)
print ('修改后的数组：\n',b)

原始数组： [0 1 2 3 4 5 6 7 8 9] 

- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
修改后的数组：
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [255]:
import numpy as np
 
a = np.arange(10).reshape(2,5) 
print ('原始数组：')
for row in a:
    print (row)
print("- -"*30)  
print(a.flat)

原始数组：
[0 1 2 3 4]
[5 6 7 8 9]
- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -


In [ ]:
'''对数组中每个元素都进行处理，可以使用flat属性，该属性是一个数组元素迭代器：'''
print ('迭代后的数组：')
for element in a.flat:
    print (element)

In [265]:
print('''numpy.ndarray.flatten 返回一份数组拷贝，对拷贝所做的修改不会影响原始数组，格式如下：

ndarray.flatten(order='C')
参数说明：

order：'C' -- 按行，'F' -- 按列，'A' -- 原顺序，'K' -- 元素在内存中的出现顺序。''')

numpy.ndarray.flatten 返回一份数组拷贝，对拷贝所做的修改不会影响原始数组，格式如下：

ndarray.flatten(order='C')
参数说明：

order：'C' -- 按行，'F' -- 按列，'A' -- 原顺序，'K' -- 元素在内存中的出现顺序。


In [266]:
import numpy as np
 
a = np.arange(10).reshape(2,5)
 
print ('原数组：',a)
print("- -"*30) 

print ('展开的数组：',a.flatten())
print("- -"*30) 
 
print ('以 F 风格顺序展开的数组：',a.flatten(order = 'F'))


原数组： [[0 1 2 3 4]
 [5 6 7 8 9]]
- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
展开的数组： [0 1 2 3 4 5 6 7 8 9]
- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
以 F 风格顺序展开的数组： [0 5 1 6 2 7 3 8 4 9]


## 反转数组

In [270]:
print('''
函数	           描述
transpose	对换数组的维度
ndarray.T	和 self.transpose() 相同
rollaxis	向后滚动指定的轴
swapaxes	对换数组的两个轴''')


函数	           描述
transpose	对换数组的维度
ndarray.T	和 self.transpose() 相同
rollaxis	向后滚动指定的轴
swapaxes	对换数组的两个轴


In [271]:
print('''numpy.transpose 函数用于对换数组的维度，格式如下：

         numpy.transpose(arr, axes)
参数说明:
arr：要操作的数组
axes：整数列表，对应维度，通常所有维度都会对换。''')

numpy.transpose 函数用于对换数组的维度，格式如下：

         numpy.transpose(arr, axes)
参数说明:
arr：要操作的数组
axes：整数列表，对应维度，通常所有维度都会对换。


In [273]:
import numpy as np
 
a = np.arange(12).reshape(3,4)
print ('原数组：\n',a)
print("- -"*30)
b = np.transpose(a) 
print ('反转数组：')
print (b)

原数组：
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
对换数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## 数组整合

In [274]:
print('''
函数	            描述
concatenate	   连接沿现有轴的数组序列
stack	       沿着新的轴加入一系列数组。
hstack	       水平堆叠序列中的数组（列方向）
vstack	       竖直堆叠序列中的数组（行方向）''')


函数	            描述
concatenate	   连接沿现有轴的数组序列
stack	       沿着新的轴加入一系列数组。
hstack	       水平堆叠序列中的数组（列方向）
vstack	       竖直堆叠序列中的数组（行方向）


### 水平组合
- hstack 函数
- concatenate函数

In [285]:
import numpy as np
 
a = np.array([[1,2],[3,4]])
 
print ('第一个数组：\n',a)

print ('\n')
b = np.array([[5,6],[7,8]])
 
print ('第二个数组：\n',b)
print("- -"*30,'行数相同')
h_ab = np.hstack((a,b))
print("hstack函数处理的对象是元组,所以需要两层括号:\n",h_ab)

第一个数组：
 [[1 2]
 [3 4]]


第二个数组：
 [[5 6]
 [7 8]]
- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- - 行数相同
hstack函数处理的对象是元组,所以需要两层括号:
 [[1 2 5 6]
 [3 4 7 8]]


In [275]:
print('''
np.concatenate 函数用于沿指定轴连接相同形状的两个或多个数组，格式如下：
               np.concatenate((a1, a2, ...), axis)
参数说明：

a1, a2, ...：相同类型的数组
axis：沿着它连接数组的轴，默认为 0''')


np.concatenate 函数用于沿指定轴连接相同形状的两个或多个数组，格式如下：
               np.concatenate((a1, a2, ...), axis)
参数说明：

a1, a2, ...：相同类型的数组
axis：沿着它连接数组的轴，默认为 0


In [278]:
import numpy as np
 
a = np.array([[1,2],[3,4]])
 
print ('第一个数组：\n',a)

print ('\n')
b = np.array([[5,6],[7,8]])
 
print ('第二个数组：\n',b)

print ('\n')
# 两个数组的维度相同
 
print ('沿轴 1 连接两个数组：行数相同')
print (np.concatenate((a,b),axis = 1))

第一个数组：
 [[1 2]
 [3 4]]


第二个数组：
 [[5 6]
 [7 8]]


沿轴 0 连接两个数组：
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


沿轴 1 连接两个数组：
[[1 2 5 6]
 [3 4 7 8]]


### 垂直组合

In [283]:
import numpy as np
 
a = np.array([[1,2],[3,4]])
 
print ('第一个数组：',a)
print ('\n')
b = np.array([[5,6],[7,8]])
 
print ('第二个数组：',b)
print ('\n')
print("- -"*30)
print ('竖直堆叠：列数相同')
v_ab = np.vstack((a,b))
print (v_ab)

第一个数组： [[1 2]
 [3 4]]


第二个数组： [[5 6]
 [7 8]]


- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
竖直堆叠：
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [282]:
import numpy as np
 
a = np.array([[1,2],[3,4]])
 
print ('第一个数组：\n',a)

print ('\n')
b = np.array([[5,6],[7,8]])
 
print ('第二个数组：\n',b)

print ('\n')

 
print ('沿轴 0 连接两个数组：列数应该相同')
print (np.concatenate((a,b)))
print ('\n')

第一个数组：
 [[1 2]
 [3 4]]


第二个数组：
 [[5 6]
 [7 8]]


沿轴 0 连接两个数组：
[[1 2]
 [3 4]
 [5 6]
 [7 8]]




## 分割数组

In [288]:
print('''
函数	  数组及操作
split	将一个数组分割为多个子数组
hsplit	将一个数组水平分割为多个子数组（按列）
vsplit	将一个数组垂直分割为多个子数组（按行）''')


函数	  数组及操作
split	将一个数组分割为多个子数组
hsplit	将一个数组水平分割为多个子数组（按列）
vsplit	将一个数组垂直分割为多个子数组（按行）


In [290]:
print('''
np.split 函数沿特定的轴将数组分割为子数组，格式如下：

np.split(ary, indices_or_sections, axis)
参数说明：

ary：被分割的数组
indices_or_sections：是一个整数，就用该数平均切分，如果是一个数组，为沿轴切分的位置（左开右闭）
axis：设置沿着哪个方向进行切分，默认为 0，横向切分，即水平方向。为 1 时，纵向切分，即竖直方向。''')


np.split 函数沿特定的轴将数组分割为子数组，格式如下：

np.split(ary, indices_or_sections, axis)
参数说明：

ary：被分割的数组
indices_or_sections：是一个整数，就用该数平均切分，如果是一个数组，为沿轴切分的位置（左开右闭）
axis：设置沿着哪个方向进行切分，默认为 0，横向切分，即水平方向。为 1 时，纵向切分，即竖直方向。


In [298]:
import numpy as np
 
a = np.arange(9)
 
print ('第一个数组：',a)
print("- -"*30)
print ('将数组分为三个大小相等的子数组：')
b = np.split(a,3)
print (b)
print ('\n')
print("- -"*30) 
print ('将数组在一维数组中表明的位置分割：')
b = np.split(a,[4,7])
print (b)
print ('\n')
print("- -"*30) 
print('split 返回的是一个列表：', type(b))

第一个数组： [0 1 2 3 4 5 6 7 8]
- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
将数组分为三个大小相等的子数组：
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
将数组在一维数组中表明的位置分割：
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]


- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
split 返回的是一个列表： <class 'list'>


In [310]:
import numpy as np

a = np.arange(16).reshape(4, 4)
print('第一个数组：')
print(a)
print('\n')
print('默认分割（0轴）：')
b = np.split(a,2)
print(b)
print('\n')

print('沿垂直方向分割：')
c = np.split(a,2,1)
print(c)
print('\n')



第一个数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


默认分割（0轴）：
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


沿垂直方向分割：
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


[array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]]), array([], shape=(0, 4), dtype=int32), array([], shape=(0, 4), dtype=int32)]


## ufunc （universal function）运算
- 这些函数能够作用于narray对象的每一个元素上，而不是针对narray对象操作，numpy提供了大量的ufunc的函数。
- 可以使用'out='关键字来指定函数返回结果存储在指定数组中

### 数学函数

In [96]:
'''- 这些函数在对narray进行运算的速度比使用循环或者列表推导式要快很多,内置的许多ufunc函数都是C语言实现的
- 但请注意，在对单个数值进行运算时，python提供的运算要比numpy效率高'''

x = np.linspace(0,2*np.pi,10).reshape(2,5)
y= np.sin(x)
print(y)
'''对于计算单个元素，则建议采用Math库里对应的函数，np.sin( )对应math.sin( )，因为对于np.sin( )为了实现数组计算，底层做了很多复杂的处理，
因此对于单个元素，math库里的函数计算速度快得多；而对于数组元素，则采用numpy库里的函数计算。'''


[[ 0.00000000e+00  6.42787610e-01  9.84807753e-01  8.66025404e-01
   3.42020143e-01]
 [-3.42020143e-01 -8.66025404e-01 -9.84807753e-01 -6.42787610e-01
  -2.44929360e-16]]


-0.8660254037844385

In [97]:
import math
math.sin(x[1,1])

-0.8660254037844385

In [98]:
import math
math.sin(x.item(1,1))

-0.8660254037844385

In [108]:
x = np.linspace(0,2*np.pi,10).reshape(2,5)
print(x.item(1,1))  #与x[1,1]类似
print('item返回python类型:',type(x.item(1,1)))
print(x[1,1])
print('通过下标获取数组元素的类型为numpy中定义的类型:',type(x[1,1]))

4.1887902047863905
item返回python类型: <class 'float'>
4.1887902047863905
通过下标获取数组元素的类型为numpy中定义的类型: <class 'numpy.float64'>


In [115]:
print('''NumPy 包含大量的各种数学运算的函数，包括三角函数，算术运算的函数，复数处理函数等。


1. numpy 提供了标准的三角函数：sin()、cos()、tan()。
2. np.around() 函数返回指定数字的四舍五入值。

np.around(a,decimals)
参数说明：a: 数组
          decimals: 舍入的小数位数。 默认值为0。 如果为负，整数将四舍五入到小数点左侧的位置.
3.np.floor() 返回小于或者等于指定表达式的最大整数，即向下取整。
4.np.ceil() 返回大于或者等于指定表达式的最小整数，即向上取整。 
''')

NumPy 包含大量的各种数学运算的函数，包括三角函数，算术运算的函数，复数处理函数等。


1. NumPy 提供了标准的三角函数：sin()、cos()、tan()。
2. np.around() 函数返回指定数字的四舍五入值。

np.around(a,decimals)
参数说明：a: 数组
          decimals: 舍入的小数位数。 默认值为0。 如果为负，整数将四舍五入到小数点左侧的位置.
3.np.floor() 返回小于或者等于指定表达式的最大整数，即向下取整。
4.np.ceil() 返回大于或者等于指定表达式的最小整数，即向上取整。 



### 算数运算

In [109]:
'''四则运算'''
print('''
算术函数包含简单的加减乘除: add()，subtract()，multiply() 和 divide()
''')
a = np.zeros(10).reshape(2,5)
a1 = np.arange(0,10).reshape(2,5)
print('第一个数组：\n',a1)
a2 = np.arange(0,20,2).reshape(2,5)
print('第二个数组：\n',a2)
a3 = np.add(a1,a2,out=a)# out =数组须是事先定义过的数组
print('- -'*30)
print(a3,'\n',a)
id(a3)==id(a)
# out 关键字指定数组与通常使用赋值方式得到的函数运算结果数组是绑定到同一对象的


算术函数包含简单的加减乘除: add()，subtract()，multiply() 和 divide()

第一个数组：
 [[0 1 2 3 4]
 [5 6 7 8 9]]
第二个数组：
 [[ 0  2  4  6  8]
 [10 12 14 16 18]]
- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
[[ 0.  3.  6.  9. 12.]
 [15. 18. 21. 24. 27.]] 
 [[ 0.  3.  6.  9. 12.]
 [15. 18. 21. 24. 27.]]


True

In [110]:
'''
np.reciprocal() 函数返回参数逐元素的倒数。
'''
import numpy as np 
a = np.array([0.25,  1.33,  1,  100])  
print ('数组是：',a)
print ('\n')
print ('调用 reciprocal 函数：')
print (np.reciprocal(a))

数组是： [  0.25   1.33   1.   100.  ]


调用 reciprocal 函数：
[4.        0.7518797 1.        0.01     ]


In [111]:
'''
np.power() 函数将第一个输入数组中的元素作为底数，计算它与第二个输入数组中相应元素的幂。
'''

import numpy as np 
 
a = np.array([10,100,1000])  
print ('数组是:',a)
print ('\n') 
print ('调用 power 函数：')
print (np.power(a,2))
print ('\n')
print ('第二个数组：')
b = np.array([1,2,3])  
print (b)
print ('\n')
print ('再次调用 power 函数：')
print (np.power(a,b))

数组是: [  10  100 1000]


调用 power 函数：
[    100   10000 1000000]


第二个数组：
[1 2 3]


再次调用 power 函数：
[        10      10000 1000000000]


In [113]:
'''
np.mod() 计算输入数组中相应元素的相除后的余数。 函数 numpy.remainder() 也产生相同的结果。'''
import numpy as np
 
a = np.array([10,20,30]) 
b = np.array([3,5,7])  
print ('第一个数组：',a)

print ('\n')
print ('第二个数组：',b)
print ('\n')
print ('调用 mod() 函数：')
print (np.mod(a,b))
print ('\n')
print ('调用 remainder() 函数：')
print (np.remainder(a,b))

第一个数组： [10 20 30]


第二个数组： [3 5 7]


调用 mod() 函数：
[1 0 2]


调用 remainder() 函数：
[1 0 2]


### 比较运算与布尔运算

In [125]:
 '''使用'=='、'>'等比较运算符比较两个数组，将返回一个布尔数组，它的每个元素的值是两个数组对应元素比较的结果.'''
a = np.array([[1,2,3],[4,5,6]]).reshape(2,3)
b = np.array([[1,2,3],[4,5,8]]).reshape(2,3)
print('python中的比较运算:\n',a==b)
print('ufunc中的比较运算-等于:\n',np.equal(a,b))

print('ufunc中的比较运算-不等于:\n',np.not_equal(a,b))

print('ufunc中的比较运算-小于:\n',np.less(a,b))
print('ufunc中的比较运算-小于等于:\n',np.less_equal(a,b))
print('ufunc中的比较运算-大于:\n',np.greater(a,b))
print('ufunc中的比较运算-大于等于:\n',np.greater_equal(a,b))

python中的比较运算:
 [[ True  True  True]
 [ True  True False]]
ufunc中的比较运算-等于:
 [[ True  True  True]
 [ True  True False]]
ufunc中的比较运算-不等于:
 [[False False False]
 [False False  True]]
ufunc中的比较运算-小于:
 [[False False False]
 [False False  True]]
ufunc中的比较运算-小于等于:
 [[ True  True  True]
 [ True  True  True]]
ufunc中的比较运算-大于:
 [[False False False]
 [False False False]]
ufunc中的比较运算-大于等于:
 [[ True  True  True]
 [ True  True False]]


In [131]:
'''由于Python的布尔运算使用and,or和Not等关键字，无法被重载，因此数组的布尔运算智能通过ufunc对应的函数来操作，这些函数以"logical_"开头'''
a1= np.arange(10)
a2=np.arange(0,20,2)
print('a1',a1)
print('a2',a2)
print(np.logical_and(a1>6,a2>15))
print('''其余的布尔运算：np.logical_not
np.logical_or
np.logical_xor''')

a1 [0 1 2 3 4 5 6 7 8 9]
a2 [ 0  2  4  6  8 10 12 14 16 18]
[False False False False False False False False  True  True]
np.logical_not
np.logical_or
np.logical_xor


### 统计函数
- numPy 提供了很多统计函数，用于从数组中查找最小元素，最大元素，百分位标准差和方差等。

In [139]:
print('''np.amin() 和 np.amax()
np.amin() 用于计算数组中的元素沿指定轴的最小值。

np.amax() 用于计算数组中的元素沿指定轴的最大值。''')

import numpy as np 
a = np.array([[3,7,5],[8,4,3],[2,4,9]])  
print ('原始的数组是：\n',a)
print ('\n')
print ('调用 amin() 函数：')
print (np.amin(a,1))#行最小
print ('\n')
print ('再次调用 amin() 函数：')
print (np.amin(a,0))
print ('\n')

np.amin() 和 np.amax()
np.amin() 用于计算数组中的元素沿指定轴的最小值。

np.amax() 用于计算数组中的元素沿指定轴的最大值。
原始的数组是：
 [[3 7 5]
 [8 4 3]
 [2 4 9]]


调用 amin() 函数：
[3 3 2]


再次调用 amin() 函数：
[2 4 3]




In [141]:
print('''np.ptp()函数计算数组中沿指定轴的元素最大值与最小值的差（最大值 - 最小值）。''')
import numpy as np 
 
a = np.array([[3,7,6],[8,2,6],[2,2,7],[1,2,3]])  
print ('原始的数组是：\n',a)
print ('\n')
print ('调用 ptp() 函数：')
print (np.ptp(a))
print ('\n')
print ('沿轴 1 调用 ptp() 函数：')
print (np.ptp(a, axis =  1))
print ('\n')
print ('沿轴 0 调用 ptp() 函数：')
print (np.ptp(a, axis =  0))

np.ptp()函数计算数组中沿指定轴的元素最大值与最小值的差（最大值 - 最小值）。
原始的数组是：
 [[3 7 6]
 [8 2 6]
 [2 2 7]
 [1 2 3]]


调用 ptp() 函数：
7


沿轴 1 调用 ptp() 函数：
[4 6 5 2]


沿轴 0 调用 ptp() 函数：
[7 5 4]


In [144]:
print('''np.percentile()
百分位数是统计中使用的度量，表示小于这个值的观察值的百分比。 函数np.percentile()接受以下参数。

np.percentile(a, q, axis)
参数说明：

a: 输入数组
q: 要计算的百分位数，在 0 ~ 100 之间
axis: 沿着它计算百分位数的轴''')
#第 p 个百分位数是这样一个值，它使得至少有 p% 的数据项小于或等于这个值，且至少有 (100-p)% 的数据项大于或等于这个值。


print('''np.median()
np.median() 函数用于计算数组 a 中元素的中位数（中值）''')

np.percentile()
百分位数是统计中使用的度量，表示小于这个值的观察值的百分比。 函数np.percentile()接受以下参数。

np.percentile(a, q, axis)
参数说明：

a: 输入数组
q: 要计算的百分位数，在 0 ~ 100 之间
axis: 沿着它计算百分位数的轴
np.median()
np.median() 函数用于计算数组 a 中元素的中位数（中值）


In [148]:
import numpy as np 
 
a = np.array([[30,65,70],[80,95,10],[50,90,60],[76,88,97]])  
 
print ('原始的数组是：\n',a)
print ('\n')
print ('70%分位数：',np.percentile(a, 70, axis=0))
print ('调用 median() 函数：')
print (np.median(a))
print ('\n')
print ('沿轴 0 调用 median() 函数：')
print (np.median(a, axis =  0))
print ('\n')
print ('沿轴 1 调用 median() 函数：')
print (np.median(a, axis =  1))

原始的数组是：
 [[30 65 70]
 [80 95 10]
 [50 90 60]
 [76 88 97]]


70%分位数： [76.4 90.5 72.7]
调用 median() 函数：
73.0


沿轴 0 调用 median() 函数：
[63. 89. 65.]


沿轴 1 调用 median() 函数：
[65. 80. 60. 88.]


In [150]:
print('''np.mean()
np.mean() 函数返回数组中元素的算术平均值。 如果提供了轴，则沿其计算。

算术平均值是沿轴的元素的总和除以元素的数量。''')

import numpy as np 
 
a = np.array([[1,2,3],[3,4,5],[4,5,6]])  
print ('原始的数组是：',a)
print ('\n')
print ('调用 mean() 函数：')
print (np.mean(a))
print ('\n')
print ('沿轴 0 调用 mean() 函数：')
print (np.mean(a, axis =  0))
print ('\n')
print ('沿轴 1 调用 mean() 函数：')
print (np.mean(a, axis =  1))

np.mean()
np.mean() 函数返回数组中元素的算术平均值。 如果提供了轴，则沿其计算。

算术平均值是沿轴的元素的总和除以元素的数量。
原始的数组是： [[1 2 3]
 [3 4 5]
 [4 5 6]]


调用 mean() 函数：
3.6666666666666665


沿轴 0 调用 mean() 函数：
[2.66666667 3.66666667 4.66666667]


沿轴 1 调用 mean() 函数：
[2. 4. 5.]


In [ ]:
print('''np.average()
np.average() 函数根据在另一个数组中给出的各自的权重计算数组中元素的加权平均值。

该函数可以接受一个轴参数。 如果没有指定轴，则数组会被展开。

加权平均值即将各数值乘以相应的权数，然后加总求和得到总体值，再除以总的单位数。

''')
'''考虑数组[1,2,3,4]和相应的权重[4,3,2,1]，通过将相应元素的乘积相加，并将和除以权重的和，来计算加权平均值。'''

In [151]:
import numpy as np 
 
a = np.array([1,2,3,4])  
print ('原始的数组是：\n',a)
print ('\n')
print ('调用 average() 函数：')
print (np.average(a))# 不指定权重时相当于 mean 函数
print ('\n')

wts = np.array([4,3,2,1])  
print ('再次调用 average() 函数：')
print (np.average(a,weights = wts))
print ('\n')
# 如果 returned 参数设为 true，则返回权重的和  
print ('权重的和：')
print (np.average([1,2,3,4],weights =  [4,3,2,1], returned =  True))

原始的数组是：
 [1 2 3 4]


调用 average() 函数：
2.5


再次调用 average() 函数：
2.0


权重的和：
(2.0, 10.0)


In [155]:
print('''
标准差是一组数据平均值分散程度的一种度量。

标准差是方差的算术平方根。

标准差公式如下：

std = sqrt(mean((x - x.mean())**2))''')
a =np.arange(10)
np.std(a)


标准差是一组数据平均值分散程度的一种度量。

标准差是方差的算术平方根。

标准差公式如下：

std = sqrt(mean((x - x.mean())**2))


2.8722813232690143

In [156]:
print('''统计中的方差（样本方差）是每个样本值与全体样本值的平均数之差的平方值的平均数，即 mean((x - x.mean())** 2)。

换句话说，标准差是方差的平方根。''')
a =np.arange(10)
np.var(a)

统计中的方差（样本方差）是每个样本值与全体样本值的平均数之差的平方值的平均数，即 mean((x - x.mean())** 2)。

换句话说，标准差是方差的平方根。


8.25

### 位运算

In [134]:
print('''numPy 中以"bitwise_" 开头的函数是位运算函数。

numPy 位运算包括以下几个函数：

函数	描述
bitwise_and	对数组元素执行位与操作
bitwise_or	对数组元素执行位或操作
invert	    按位取反
left_shift	向左移动二进制表示的位
right_shift	向右移动二进制表示的位
注：也可以使用 "&"、 "~"、 "|" 和 "^" 等操作符进行计算。''')

numPy 中以"bitwise_" 开头的函数是位运算函数。

numPy 位运算包括以下几个函数：

函数	描述
bitwise_and	对数组元素执行位与操作
bitwise_or	对数组元素执行位或操作
invert	    按位取反
left_shift	向左移动二进制表示的位
right_shift	向右移动二进制表示的位
注：也可以使用 "&"、 "~"、 "|" 和 "^" 等操作符进行计算。


### 自定义ufunc函数

In [159]:
print('''除了numpy内置ufunc函数，用户也可以自定义的ufunc函数.具体地，

1. 编写对单个数值计算的目的函数； 

def add_elements(x, y):
    return x + y
2. 
使用frompyfunc或者vectorize可以将计算单个元素的函数转换成对数组中每个元素的ufunc函数

利用np.frompyfunc(func, nin, nout)将其转换为ufunc函数
func：自己编写的目的函数，
nin： 参数个数
nout：返回值个数

np.frompyfunc的返回值其类型均为object，通过astype()方法可以将类型做出相应的转换；

np.vectorize(func, otypes=[])函数指定两个参数，依次为：标量参数、返回值的类型列表''')

除了numpy内置ufunc函数，用户也可以自定义的ufunc函数.具体地，

1. 编写对单个数值计算的目的函数； 

def add_elements(x, y):
    return x + y
2. 
使用frompyfunc或者vectorize可以将计算单个元素的函数转换成对数组中每个元素的ufunc函数

利用np.frompyfunc(func, nin, nout)将其转换为ufunc函数
func：自己编写的目的函数，
nin： 参数个数
nout：返回值个数

np.frompyfunc的返回值其类型均为object，通过astype()方法可以将类型做出相应的转换；

np.vectorize(func, otypes=[])函数指定两个参数，依次为：标量参数、返回值的类型列表


In [187]:
'''出题难度大，需要对所有人的分数提升，且保持分数的相对位置不变'''
def liftscore(n):
    n_new =np.sqrt((n^2)*100)#^位异或运算
    n_new = n_new if n_new <=100 else 100
    return np.around(n_new,2)

score = np.array([87,77,56,100,60])
score_1 = np.frompyfunc(liftscore,1,1)(score)
print(score_1)

score_2 =score_1.astype(int)
print(score_2)
score_2.dtype

[92.2 88.88 76.16 100 78.74]
[ 92  88  76 100  78]


dtype('int32')

In [189]:
score_3 = np.vectorize(liftscore,otypes=[int])(score)
score_3
any(score_2 ==score_3)

True

### ufunc的方法

In [196]:
print('''ufunc函数对象本身还有一些方法函数，这些方法只对两个输入、一个输出的ufunc 函数有效
(1) reduce()方法沿着指定轴对数组进行操作，相当于将相应的操作放到该轴元素之间
''')

ufunc函数对象本身还有一些方法函数，这些方法只对两个输入、一个输出的ufunc 函数有效
(1) reduce()方法于与Python基本靠库中的reduce 函数类似，沿着指定轴对数组进行操作，相当于将相应的操作放到该轴元素之间



In [206]:
'''reduce(function, sequence[, initial]) 
参数说明：
function	有两个参数的函数, 必需参数
sequence	tuple,list ,dictionary,string等可迭代物，必需参数
initial	初始值,可选参数

reduce的工作过程是 ：在迭代sequence(tuple,list,dictionary, string等可迭代物)的过程中,首先把前两个元素传给 函数参数,
函数加工后,然后把得到的结果和第三个元素作为两个参数传给函数参数, 函数加工后得到的结果又和第四个元素作为两个参数传给函数参数,
依次类推。 如果传入了 initial 值, 那么首先传的就不是 sequence 的第一个和第二个元素,而是 initial值和 第一个元素。
经过这样的累计计算之后合并序列到一个单一返回值.
'''
def add(x, y):
    return x+y
from functools import reduce
reduce(add, [1,2,3,4])

[[1 2 3 4]
 [5 6 7 8]]


10

In [ ]:
x =np.array([[1,2,3,4],[5,6,7,8]])
print(x)
np.add.reduce(x,axis=0)
#help(np.add.reduce)

In [208]:
'''
(2) accumulate()和reduce()的关系就想cumsum 和sum 的关系,即它返回的数组和输入数组的形状相同，同时保存所有中间的结果：'''
x =np.array([[1,2,3,4],[5,6,7,8]])
print(x)
np.add.accumulate(x,axis=1)

[[1 2 3 4]
 [5 6 7 8]]


array([[ 1,  3,  6, 10],
       [ 5, 11, 18, 26]], dtype=int32)

In [211]:
'''(3) reduceat()方法用于部分reduce计算，通过indices参数指定一系列的起始和终止位置'''
x =np.arange(8)
print(x)
np.add.reduceat(x,indices=[1,4,1,5,2,6,3,7])

[0 1 2 3 4 5 6 7]


array([ 6,  4, 10,  5, 14,  6, 18,  7], dtype=int32)

In [218]:
'''(4) outer() 可对其作为两个参数的数组的没每两对元素的组合进行运算'''
a =[1,2,3,4]
b =[5,6,7,8]
print('加和:\n',np.add.outer(a,b))
print('乘积:\n',np.multiply.outer(a,b))

加和:
 [[ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]]
乘积:
 [[ 5  6  7  8]
 [10 12 14 16]
 [15 18 21 24]
 [20 24 28 32]]


## 广播

In [ ]:
'''广播(Broadcast)是 numpy 对不同形状(shape)的数组进行数值计算的方式， 对数组的算术运算通常在相应的元素上进行。

如果两个数组 a 和 b 形状相同，即满足 a.shape == b.shape，那么 a*b 的结果就是 a 与 b 数组对应位相乘。这要求维数相同，且各维度的长度相同。'''

In [190]:
import numpy as np 
 
a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a * b 
print (c)

[ 10  40  90 160]


In [192]:
import numpy as np 
 
a = np.array([[ 0, 0, 0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])
b = np.array([1,2,3])
print(np.add(a,b))

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


- - 广播的规则:

- 让所有输入数组都向其中形状最长的数组看齐，形状中不足的部分都通过在前面加 1 补齐。 如上例中b由(1,3)变成 (2,3)
- 输出数组的形状是输入数组形状的各个维度上的最大值。
- 如果输入数组的某个维度和输出数组的对应维度的长度相同或者其长度为 1 时，这个数组能够用来计算，否则出错。
- 当输入数组的某个维度的长度为 1 时，沿着此维度运算时都用此维度上的第一组值。

##  数组元素的添加与删除

In [311]:
print('''
函数	     元素及描述
resize	返回指定形状的新数组
reshape  返回指定形状的新数组 
append	将值添加到数组末尾
insert	沿指定轴将值插入到指定下标之前
delete	删掉某个轴的子数组，并返回删除后的新数组
unique	查找数组内的唯一元素''')


函数	     元素及描述
resize	返回指定形状的新数组
append	将值添加到数组末尾
insert	沿指定轴将值插入到指定下标之前
delete	删掉某个轴的子数组，并返回删除后的新数组
unique	查找数组内的唯一元素


### resize 函数

In [14]:
print('''np.resize 函数返回指定大小的新数组。如果新数组大小大于原始大小，则包含原始数组中的元素的副本。
        np.resize(arr, shape)
参数说明：
arr：要修改大小的数组
shape：返回数组的新形状'''
)
#help(np.resize)

np.resize 函数返回指定大小的新数组。如果新数组大小大于原始大小，则包含原始数组中的元素的副本。
        np.resize(arr, shape)
参数说明：
arr：要修改大小的数组
shape：返回数组的新形状


In [11]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print('- -'*30,'第一个数组')
 
print ('第一个数组：\n',a)
 
print ('第一个数组的形状：\n',a.shape)
print('- -'*30,'第二个数组')

b = np.resize(a, (3,2))
 
print ('第二个数组：\n',b) 
print ('第二个数组的形状：\n', b.shape)
print('- -'*30,'第三个数组')
 
print ('修改第一个数组的大小：')
b = np.resize(a,(3,3))# 要注意 a 的第一行在 b 中重复出现，因为尺寸变大了
print (b)


- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- - 第一个数组
第一个数组：
 [[1 2 3]
 [4 5 6]]
第一个数组的形状：
 (2, 3)
- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- - 第二个数组
第二个数组：
 [[1 2]
 [3 4]
 [5 6]]
第二个数组的形状：
 (3, 2)
- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- - 第三个数组
修改第一个数组的大小：
[[1 2 3]
 [4 5 6]
 [1 2 3]]


### reshape 函数

In [33]:
#help(np.reshape)
print('''语法：np.reshape(a, newshape, order='C')
   参数说明：
   a：要修改大小的数组
   newshape：返回数组的新形状
   order={'C', 'F', 'A'}''')

语法：np.reshape(a, newshape, order='C')
   参数说明：
   a：要修改大小的数组
   newshape：返回数组的新形状
   order={'C', 'F', 'A'}


In [35]:
import numpy as np
a = np.array([[1,2,3], [4,5,6]])
b = np.reshape(a, (2,3))
print(b)

[[1 2 3]
 [4 5 6]]


In [39]:
print('''如果newshape里面的有负数''')
a = np.array([[1,2,3], [4,5,6]])
b1 = np.reshape(a,(3,-1))
print(b1)
# 将a变成3行的格式，列数自动计算的(c=2, d=6/3=2)
print('- -'*10)
a = np.array([[1,2,3], [4,5,6]])
b1 = np.reshape(a,(-1,3))
print(b1)

如果newshape里面的有负数
[[1 2]
 [3 4]
 [5 6]]
- -- -- -- -- -- -- -- -- -- -
[[1 2 3]
 [4 5 6]]


In [20]:
print('- -'*10,'关于order 这一参数的详解（源自help(np.reshape)的翻译）','- -'*10)
print('''order 的翻译：order : 可选范围为{'C', 'F', 'A'}。使用索引顺序读取a的元素，并按照索引顺序将元素放到变换后的的数组中。
         如果不进行order参数的设置，默认参数为C。

（1）“C”指的是用类C写的读/索引顺序的元素，最后一个维度变化最快，第一个维度变化最慢。以二维数组为例，简单来讲就是横着读，横着写，
     优先读/写一行。
（2）“F”是指用FORTRAN类索引顺序读/写元素，最后一个维度变化最慢，第一个维度变化最快。竖着读，竖着写，优先读/写一列。注意，“C”和“F”
      选项不考虑底层数组的内存布局，只引用索引的顺序。

（3）“A”选项所生成的数组的效果与原数组a的数据存储方式有关，如果数据是按照FORTRAN存储的话，它的生成效果与”F“相同，否则与“C”相同。
   这里可能听起来有点模糊，下面会给出示例。

注：FORTRAN和C是两个语言，他们存储数组的方式不同，FORTRSAN为列有限，而C为行优先。在python中默认数组生成的时候是按照C的方式进行存储。
    但很多时候我们需要调用Fortran的一些库进行数学计算，所以需要让numpy生成的数组变成按照FORTRAN的方式存储
''')

- -- -- -- -- -- -- -- -- -- - 关于order 这一参数的详解（源自help(np.reshape)的翻译） - -- -- -- -- -- -- -- -- -- -
order 的翻译：order : 可选范围为{'C', 'F', 'A'}。使用索引顺序读取a的元素，并按照索引顺序将元素放到变换后的的数组中。
         如果不进行order参数的设置，默认参数为C。

（1）“C”指的是用类C写的读/索引顺序的元素，最后一个维度变化最快，第一个维度变化最慢。以二维数组为例，简单来讲就是横着读，横着写，
     优先读/写一行。
（2）“F”是指用FORTRAN类索引顺序读/写元素，最后一个维度变化最慢，第一个维度变化最快。竖着读，竖着写，优先读/写一列。注意，“C”和“F”
      选项不考虑底层数组的内存布局，只引用索引的顺序。

（3）“A”选项所生成的数组的效果与原数组a的数据存储方式有关，如果数据是按照FORTRAN存储的话，它的生成效果与”F“相同，否则与“C”相同。
   这里可能听起来有点模糊，下面会给出示例。

注：FORTRAN和C是两个语言，他们存储数组的方式不同，FORTRSAN为列有限，而C为行优先。在python中默认数组生成的时候是按照C的方式进行存储。
    但很多时候我们需要调用Fortran的一些库进行数学计算，所以需要让numpy生成的数组变成按照FORTRAN的方式存储



In [32]:
r = np.arange(12)
print("原数组:\n",r)

ar1=r.reshape((3,4),order='A')
ar2=r.reshape((3,4),order='C')
ar3=r.reshape((3,4),order='F')
ar4=r.reshape((3,4))
 

print('- -'*10,"按照order=A排序：\n",ar1)
print('- -'*10,"按照order=C排序：\n",ar2)
print('- -'*10,"按照order=F排序：\n",ar3)
print('- -'*10,"默认排序:\n",ar4)

原数组:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
- -- -- -- -- -- -- -- -- -- - 按照order=A排序：
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
- -- -- -- -- -- -- -- -- -- - 按照order=C排序：
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
- -- -- -- -- -- -- -- -- -- - 按照order=F排序：
 [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
- -- -- -- -- -- -- -- -- -- - 默认排序:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### append函数

In [43]:
print('''
np.append 函数在数组的末尾添加值。 追加操作会分配整个数组，并把原来的数组复制到新数组中。 
此外，输入数组的维度必须匹配否则将生成ValueError。
np.append(arr, values, axis=None)
参数说明：
arr：输入数组
values：要向arr添加的值，需要和arr形状相同（除了要添加的轴）
axis：默认为 None。当axis无定义时，是横向加成，返回总是为一维数组！当axis有定义的时候，
分别为0和1的时候。当 axis 为0时，数组是加在下面（列数要相同）。当axis为1时，数组是加在右边（行数要相同）。''')


np.append 函数在数组的末尾添加值。 追加操作会分配整个数组，并把原来的数组复制到新数组中。 
此外，输入数组的维度必须匹配否则将生成ValueError。
np.append(arr, values, axis=None)
参数说明：
arr：输入数组
values：要向arr添加的值，需要和arr形状相同（除了要添加的轴）
axis：默认为 None。当axis无定义时，是横向加成，返回总是为一维数组！当axis有定义的时候，
分别为0和1的时候。当 axis 为0时，数组是加在下面（列数要相同）。当axis为1时，数组是加在右边（行数要相同）。


In [42]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]])
 
print ('第一个数组：\n',a)
 
print ('向数组添加元素：')
print (np.append(a, [7,8,9]))
print ('\n')
 
print ('沿轴 0 添加元素：')
print (np.append(a, [[7,8,9]],axis = 0))
print ('\n')
 
print ('沿轴 1 添加元素：')
print (np.append(a, [[5,5,5],[7,8,9]],axis = 1))

第一个数组：
 [[1 2 3]
 [4 5 6]]
向数组添加元素：
[1 2 3 4 5 6 7 8 9]


沿轴 0 添加元素：
[[1 2 3]
 [4 5 6]
 [7 8 9]]


沿轴 1 添加元素：
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


### insert 函数

In [ ]:
print('''np.insert
np.insert 函数在给定索引之前，沿给定轴在输入数组中插入值。

如果值的类型转换为要插入，则它与输入数组不同。 插入没有原地的，函数会返回一个新数组。 此外，如果未提供轴，则输入数组会被展开。

np.insert(arr, obj, values, axis)
参数说明：

arr：输入数组
obj：在其之前插入值的索引
values：要插入的值
axis：沿着它插入的轴，如果未提供，则输入数组会被展开''')


In [44]:
import numpy as np 
a = np.array([[1,2],[3,4],[5,6]])
 
print ('第一个数组：')
print (a)
print ('\n')
 
print ('未传递 Axis 参数。 在插入之前输入数组会被展开。')
print (np.insert(a,3,[11,12]))
print ('\n')
print ('传递了 Axis 参数。 会广播值数组来配输入数组。')
 
print ('沿轴 0 广播：')
print (np.insert(a,1,[11],axis = 0))
print ('\n')
 
print ('沿轴 1 广播：')
print (np.insert(a,1,11,axis = 1))

第一个数组：
[[1 2]
 [3 4]
 [5 6]]


未传递 Axis 参数。 在插入之前输入数组会被展开。
[ 1  2  3 11 12  4  5  6]


传递了 Axis 参数。 会广播值数组来配输入数组。
沿轴 0 广播：
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]


沿轴 1 广播：
[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]


###  delete 函数

In [46]:
print('''np.delete 函数返回从输入数组中删除指定子数组的新数组。 与 insert() 函数的情况一样，如果未提供轴参数，则输入数组将展开。

np.delete(arr, obj, axis)
参数说明：

arr：输入数组
obj：可以被切片，整数或者整数数组，表明要从输入数组删除的子数组
axis：沿着它删除给定子数组的轴，如果未提供，则输入数组会被展开
''')

np.delete 函数返回从输入数组中删除指定子数组的新数组。 与 insert() 函数的情况一样，如果未提供轴参数，则输入数组将展开。

np.delete(arr, obj, axis)
参数说明：

arr：输入数组
obj：可以被切片，整数或者整数数组，表明要从输入数组删除的子数组
axis：沿着它删除给定子数组的轴，如果未提供，则输入数组会被展开



In [ ]:
import numpy as np
a = np.arange(12).reshape(3,4)
 
print ('第一个数组：',a)
print ('\n')
 
print ('未传递 Axis 参数。 在插入之前输入数组会被展开。')
print (np.delete(a,5))
print ('\n')
 
print ('删除第二列：')
print (np.delete(a,1,axis = 1))
print ('\n')
 
print ('包含从数组中删除的替代值的切片：')
a = np.array([1,2,3,4,5,6,7,8,9,10])
print (np.delete(a, np.s_[::2]))

### unique 函数

In [ ]:
print('''np.unique
np.unique 函数用于去除数组中的重复元素。

np.unique(arr, return_index, return_inverse, return_counts)
参数说明：

arr：输入数组，如果不是一维数组则会展开
return_index：如果为true，返回新列表元素在旧列表中的位置（下标），并以列表形式储
return_inverse：如果为true，返回旧列表元素在新列表中的位置（下标），并以列表形式储
return_counts：如果为true，返回去重数组中的元素在原数组中的出现次数''')

In [47]:
import numpy as np
a = np.array([5,2,6,2,7,5,6,8,2,9])
 
print ('第一个数组：',a)
print ('\n')
 
print ('第一个数组的去重值：')
u = np.unique(a)
print (u)
print ('\n')
 
print ('去重数组的索引数组：')
u,indices = np.unique(a, return_index = True)
print (indices)
print ('\n')
 
print ('我们可以看到每个和原数组下标对应的数值：',a)
print ('\n')
 
print ('去重数组的下标：')
u,indices = np.unique(a,return_inverse = True)
print (u)
print ('\n')
 
print ('下标为：')
print (indices)
print ('\n')
 
print ('使用下标重构原数组：')
print (u[indices])
print ('\n')
 
print ('返回去重元素的重复数量：')
u,indices = np.unique(a,return_counts = True)
print (u)
print (indices)

第一个数组： [5 2 6 2 7 5 6 8 2 9]


第一个数组的去重值：
[2 5 6 7 8 9]


去重数组的索引数组：
[1 0 2 4 7 9]


我们可以看到每个和原数组下标对应的数值： [5 2 6 2 7 5 6 8 2 9]


去重数组的下标：
[2 5 6 7 8 9]


下标为：
[1 0 2 0 3 1 2 4 0 5]


使用下标重构原数组：
[5 2 6 2 7 5 6 8 2 9]


返回去重元素的重复数量：
[2 5 6 7 8 9]
[3 2 2 1 1 1]


## 排序、条件刷选函数

In [4]:
'''numpy.sort()
numpy.sort() 函数返回输入数组的排序副本。函数格式如下：

numpy.sort(a, axis, kind, order)
参数说明：

a: 要排序的数组
axis: 沿着它排序数组的轴，如果没有数组会被展开，沿着最后的轴排序， axis=0 按列排序，axis=1 按行排序
kind: 默认为'quicksort'（快速排序）
order: 如果数组包含字段，则是要排序的字段'''

'''种类	             速度 	最坏情况	工作空间	稳定性
'quicksort'（快速排序）	1	O(n^2)	0	否
'mergesort'（归并排序）	2	O(n*log(n))	~n/2	是
'heapsort'（堆排序）	3	O(n*log(n))	0	否'''
import numpy as np  
 
a = np.array([[3,7],[9,1]])  
print ('原始的数组是：\n',a)
print ('\n')

print ('调用 sort() 函数：')
print (np.sort(a))
print ('\n')
print ('按行排序：')
print (np.sort(a, axis =  1))
print ('\n')
# 在 sort 函数中排序字段 
dt = np.dtype([('name',  'S10'),('age',  int)]) 
a = np.array([("raju",21),("anil",25),("ravi",  17),  ("amar",27)], dtype = dt)  
print ('原始的的数组是：')
print (a)
print ('\n')
print ('按 name 排序：')
print (np.sort(a, order =  'name'))

原始的数组是：
 [[3 7]
 [9 1]]


调用 sort() 函数：
[[3 7]
 [1 9]]


按行排序：
[[3 7]
 [1 9]]


原始的的数组是：
[(b'raju', 21) (b'anil', 25) (b'ravi', 17) (b'amar', 27)]


按 name 排序：
[(b'amar', 27) (b'anil', 25) (b'raju', 21) (b'ravi', 17)]


Help on function sort in module numpy:

sort(a, axis=-1, kind=None, order=None)
    Return a sorted copy of an array.
    
    Parameters
    ----------
    a : array_like
        Array to be sorted.
    axis : int or None, optional
        Axis along which to sort. If None, the array is flattened before
        sorting. The default is -1, which sorts along the last axis.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
        and 'mergesort' use timsort or radix sort under the covers and, in general,
        the actual implementation will vary with data type. The 'mergesort' option
        is retained for backwards compatibility.
    
        .. versionchanged:: 1.15.0.
           The 'stable' option was added.
    
    order : str or list of str, optional
        When `a` is an array with fields defined, this argument specifies
        which fields to compare first, second, etc.  A si